[project]
name = "modelviewprojection"
version = "0.0.2"
authors = [{name="William Emerison Six", email="billsix@gmail.com"}]
description = "ModelViewProjection - Tutorial for learning 3D Programming"

dependencies = [
    "autoflake",
    "sphinxcontrib-bibtex",
    "furo",
    "glfw",
    "imageio",
    "isort",
    "jupyter",
    "jupytext",
    "mathjax",
    "matplotlib",
    "moviepy",
    "myst-nb",
    "numpy",
    "PyOpenGL",
    "pytest",
    "Sphinx",
    "sphinx-rtd-theme",
    "nbsphinx",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest]
testpaths = ["tests"]

[tools.ruff]
select = ['F401', 'F811', 'E402', 'I001', 'TID252', "F841", "E302", "E231", "B006", "B007", "B008", "UP007", "UP035", "S311", "S602", "T201"]
ignore = []

[tool.ruff.lint]
select = ["E", "F", "I"]

[project.scripts]
generate_plots_for_book = "modelviewprojection.plotsforbook.generate_plots:main"
